### PR TITLE
Remove special files from index

### PR DESCRIPTION
**Pull request by krishicks**
github.com/onsi/ginkgo and github.com/onsi/gomega got into a state where
they were marked as being special files in the index.

This was causing 'git submodule update' to fail because it could not
find a mapping for these special files in the index within .gitmodules.

'git submodule update' is run by 'go get -u', which was failing.

http://stackoverflow.com/questions/4185365/no-submodule-mapping-found-in-gitmodule-for-a-path-thats-not-a-submodule

See the whatchanged for this commit:

160000 ... D Godeps/_workspace/src/github.com/onsi/gomega
160000 ... D Godeps/_workspace/src/github.com/onsi/ginkgo

160000 is the file mode for special files in the index.

Signed-off-by: Kris Hicks <khicks@pivotal.io>

### CODE REVIEW

**Comment by krishicks** [comment]
It's interesting to note that this was only a problem when running GO15VENDOREXPERIMENT=1 go get -u. I'm not sure why it fails this way, but it does.

**Comment by maximilien** [comment]
I've updated dependencies and fixed this. Try to see if that works, if not let me know.

Sorry about delay. I saw this when going on vacation and fell through the cracks until recently.

Cheers :beers:

**Comment by krishicks** [comment]
Why didn't you accept the PR?

**Comment by maximilien** [comment]
I had already updated dependencies on my workspace and once I pushed I noticed your PR again and I believe my update already fixed what you mentioned.

If you have anything else you want to contribute, please submit new PR and I'll review and merge if all good.

**Pull request closed without merging**
